import os
# print(os.getcwd())
# os.chdir('gg')#改变工作路径
# print(os.getcwd())
# os.chdir('..')
# print(os.getcwd())
# os.makedirs('kh/gh')
# os.removedirs('nn/ll/kl')#只能删除目录为空的文件夹
# os.mkdir('nn/ll/kl')
# print(os.listdir())
# print(os.listdir('kh'))
# os.rename('ff,hh','gh')
# os.rename('osmb.py','os-mb.py')
# print(os.stat('os-mb.py'))#相关文件信息
# print(os.sep)
# print(os.linesep)
# print(os.path.split('kk'))#返回目录和文件名二元组
# os.path.dirname('gh')
# os.path.join(a,b)#地址拼接